apiVersion: v1
kind: Service
metadata:
  name: zomato-clone-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: zomato-clone-app